
db:
    image: postgres
    ports:
     - "8132:5432"
    environment:
     - "POSTGRES_PASSWORD=gagAdmin"

upsource-server-instance:
    image: jetbrains/upsource:2017.3.2774
    user: root
    ports:
    - "8113:8080"
    volumes:
    - "/home/upsource/data:/opt/upsource/data"
    - "/home/upsource/conf:/opt/upsource/conf"
    - "/var/log/upsource:/opt/upsource/logs"
    - "/var/backup/upsource:/opt/upsource/backups"

teamcity-server-instance:
    image: jetbrains/teamcity-server
    user: root
    ports:
    - "8111:8111"
    volumes:
    - "/home/teamcity/data:/data/teamcity_server/datadir"
    - "/var/log/teamcity:/opt/upsource/logs"
    links:
    - "db:database"

youtrack-server-instance:
    image: uniplug/youtrack
    user: root
    ports:
    - "8112:80"
    volumes:
    - "/home/youtrack/data:/opt/youtrack/data"
    - "/var/backup/youtrack:/opt/youtrack/backup"

teamcity-ubuntuagent-instance:
    image: jetbrains/teamcity-agent
    volumes:
    - "/home/teamcity_agent/data:/data/teamcity_agent/conf"
    environment:
    - "SERVER_URL=http://myteamcityurl:8111"
    - "AGENT_NAME=dockerAgentUbuntu"
